AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    burnedover-mush-appsync-api

    SAM Template for the AppSync API for burnedover-mush

Parameters:
    TablePrefix:
        Type: String
        Default: 'burnedoverdev'
        Description: (Required) The name of the new DynamoDB to store connection identifiers for each connected clients. Minimum 3 characters
        MinLength: 3
        MaxLength: 50
        AllowedPattern: ^[A-Za-z_]+$
        ConstraintDescription: 'Required. Can be characters and underscore only. No numbers or special characters allowed.'
    PermanentsStack:
        Type: String
        Default: 'BurnedOverDevPermanentsStack'
        Description: (Required) The name of the stack containing the permanents DynamoDB table.
        MinLength: 3
        MaxLength: 50
        AllowedPattern: ^[A-Za-z_]+$
        ConstraintDescription: 'Required. Can be characters and underscore only. No numbers or special characters allowed.'
    UserPoolId:
        Type: String
        Default: 'us-east-1_1pA2i23sY'
        Description: The physical ID of the cognito user pool that the API should validate against.

Resources:
    AppSyncAPI:
        Type: AWS::AppSync::GraphQLApi
        Properties:
            Name: !Sub ${TablePrefix}AppSyncAPI
            AuthenticationType: AMAZON_COGNITO_USER_POOLS
            UserPoolConfig:
                AwsRegion: us-east-1
                UserPoolId: !Ref UserPoolId
                DefaultAction: ALLOW
    CharacterTablePolicy:
        Type: AWS::IAM::ManagedPolicy
        Properties:
            PolicyDocument:
                Version: "2012-10-17"
                Statement:
                  - Effect: "Allow"
                    Action:
                        - "dynamodb:GetItem"
                        - "dynamodb:BatchGetItem"
                        - "dynamodb:Query"
                        - "dynamodb:PutItem"
                    Resource:
                        Fn::ImportValue:
                            !Sub "${PermanentsStack}-CharactersArn"
    AppSyncAPIExecutionRole:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument:
                Statement:
                  - Effect: Allow
                    Principal:
                        Service: appsync.amazonaws.com
                    Action:
                        - sts:AssumeRole
            ManagedPolicyArns:
                - !Ref CharacterTablePolicy         
    CharacterDynamoDBTableDataSource:
        Type: AWS::AppSync::DataSource
        Properties:
            ApiId: !GetAtt AppSyncAPI.ApiId
            Name: Character
            Type: AMAZON_DYNAMODB
            ServiceRoleArn: !GetAtt "AppSyncAPIExecutionRole.Arn"
            DynamoDBConfig:
                AwsRegion: us-east-1
                TableName: !Sub ${TablePrefix}_characters
    QueryGetCharacterResolver:
        Type: AWS::AppSync::Resolver
        DependsOn: Schema
        Properties:
            ApiId: !GetAtt AppSyncAPI.ApiId
            TypeName: Query
            FieldName: getCharacter
            DataSourceName: !GetAtt CharacterDynamoDBTableDataSource.Name
            RequestMappingTemplate: >
                {
                    "version": "2017-02-28",
                    "operation": "GetItem",
                    "key": {
                        "PlayerSub": $util.dynamodb.toDynamoDBJson($ctx.args.playerSub),
                        "Name": $util.dynamodb.toDynamoDBJson($ctx.args.name)
                    }
                }
            ResponseMappingTemplate: "$utils.toJson($ctx.result)"
    QueryPlayerCharactersResolver:
        Type: AWS::AppSync::Resolver
        DependsOn: Schema
        Properties:
            ApiId: !GetAtt AppSyncAPI.ApiId
            TypeName: Query
            FieldName: getPlayerCharacters
            DataSourceName: !GetAtt CharacterDynamoDBTableDataSource.Name
            RequestMappingTemplate: >
                {
                    "version": "2017-02-28",
                    "operation": "Query",
                    "query": {
                        "expression": "PlayerSub = :PlayerSub",
                        "expressionValues": {
                            ":PlayerSub": $util.dynamodb.toDynamoDBJson($ctx.identity.sub)
                        }
                    }
                }
            ResponseMappingTemplate: "$utils.toJson($ctx.result.items)"
    PutCharacterResolver:
        Type: AWS::AppSync::Resolver
        DependsOn: Schema
        Properties:
            ApiId: !GetAtt AppSyncAPI.ApiId
            TypeName: Mutation
            FieldName: putCharacter
            DataSourceName: !GetAtt CharacterDynamoDBTableDataSource.Name
            RequestMappingTemplate: >
                #if(!($ctx.args.CharacterId))
                    $util.qr($ctx.args.put("CharacterId", $util.autoId()))
                #end
                #set( $ddb = $util.dynamodb )
                {
                    "version": "2017-02-28",
                    "operation": "PutItem",
                    "key": {
                        "PlayerSub": $ddb.toStringJson($ctx.identity.sub),
                        "Name": $ddb.toStringJson($ctx.args.Name)
                    },
                    "attributeValues": {
                        "CharacterId": $ddb.toStringJson($ctx.args.CharacterId)
                        #if($ctx.args.Pronouns), "Pronouns": $ddb.toStringJson($ctx.args.Pronouns) #end
                        #if($ctx.args.FirstImpression), "FirstImpression": $ddb.toStringJson($ctx.args.FirstImpression) #end
                        #if($ctx.args.OneCoolThing), "OneCoolThing": $ddb.toStringJson($ctx.args.OneCoolThing) #end
                        #if($ctx.args.Outfit), "Outfit": $ddb.toStringJson($ctx.args.Outfit) #end
                    }
                }
            ResponseMappingTemplate: "$utils.toJson($ctx.result)"
    Schema:
        Type: AWS::AppSync::GraphQLSchema
        Properties:
            ApiId: !GetAtt AppSyncAPI.ApiId
            Definition: >
                type Character {
                    PlayerSub: String!
                    Name: String!
                    CharacterId: String!
                    Pronouns: String
                    FirstImpression: String
                    Outfit: String
                    OneCoolThing: String
                }
                type Mutation {
                    putCharacter(
                        Name: String!,
                        CharacterId: String,
                        Pronouns: String,
                        FirstImpression: String,
                        Outfit: String,
                        OneCoolThing: String
                    ): Character
                }
                type Query {
                    getCharacter(playerSub: String!, name: String!): Character
                    getPlayerCharacters: [Character]
                }
                type Subscription {
                    changedCharacter: Character
                    @aws_subscribe(mutations: ["putCharacter"])
                }
                schema {
                    mutation: Mutation
                    query: Query
                    subscription: Subscription
                }
